### ISSUE TITLE
Allow customization of each columns width

### ISSUE THREAD

**Issue by DHS1** [quodroc/HumbleNewTabPage#18]
Hello,

First I want to say how much I love this extension. I use it so many times every day at work and home. It has been a real help in efficiency and joy to use. 

Because I use it so much, I have it very customized to my liking, as much as the options allow. One thing I would really like is to have the option to re-size each individual columns width. This is because one of my columns is a list of bookmarks whose text length exceeds the maximum allowed column width for most of the bookmarks in the list, while I have another column whose list of bookmarks have a text length that is very much under the set column width. I could make both columns bookmarks fully readable if I were able to slide the "slimmer" column over, giving room to the "wider" column to display the full text of each bookmark. 

If this is already possible by Custom CSS, please let me know how it can be done! I have 4 columns currently. My "Generated CSS" is as follows: Is there a way to modify the width of each of my 4 columns individually here?

``` CSS
#main a { font-family: "Calibri"; }
#main a { font-size: 2.4em; }
#main a { color: #bfdfff; }
body { background-color: #e90740; }
#main a:hover { background-color: #e90740; }
#main a:hover { color: #b7f4ff; }
#main a:hover { box-shadow: 0 0 7px #313131; }
body { background-image: url(); }
body { background-position: top; }
body { background-repeat: no-repeat; }
#main a:hover { box-shadow: 0 0 7px #313131; }
#main a { border-radius: 0.2em; }
#main a { -webkit-transition-duration: 0.2s; }
#main a { line-height: 2; padding-left: 0.8em; padding-right: 0.8em; }
#main { width: 100%; }
#main { left: 0%; }
#main { margin-top: 7.549999999999999%; }
.wrap { -webkit-transition-duration: 0.2s; }
#options_button { opacity: 0; }
```

Thanks again for the great extension. Many in my office have switched to using it as their homepage too. Giving the option to set the background image is a small but great feature. Without it, it wouldn't be able to be as eye appealing as other competitors New Tab extensions, and I may have moved on, even with the great functionality it offers. Thanks!

**Comment by omega3** [comment]
@ibillingsley 
Is it possible to use css to fold column of Bookmarks Toolbar so that it doesn't need to be scrolled down and display bookmarks in second column - the same as you write on one paper page to the bottom and start from the top of next page? Or better to make this column like 1200 pixels and display bookmarks inline, the same way as they are visible on Bookmarks Toolbar?

**Comment by ibillingsley** [comment]
You can do something like:
```css
/* Split the first column into 2, using 50% of total width (assuming 2 other columns) */
.column:nth-child(1) { column-count: 2; width: 50% !important; }
/* Reduce the width of the other columns */
.column { width: 25% !important; }
```
Depending on the number of columns, adjust the widths accordingly.

To display them inline, you could try something like:
```css
/* Use 50% of total width for the first column */
.column:nth-child(1) { width: 50% !important; }
/* Display first column links inline */
.column:nth-child(1) li { display: inline; white-space: normal; }
/* Reduce the width of the other columns */
.column { width: 25% !important; }
```
Might look a little messy, especially if you have subfolders in there.
