### ISSUE TITLE
request:humblenewpage button next to options button

### ISSUE THREAD

**Issue by noisefield** [quodroc/HumbleNewTabPage#44]
wish for a small feature, a humblepage button like the options button, when we click it, we would just see the picture or the color chosen to the humblenewpage background, then we click it and we see all the folders and links again, a simple "on/off" button. Thanks!

**Comment by noisefield** [comment]
..or  instead of a button  a double click option in any part of the page to turn on/off links/folders or (other option) even turn on/off humblenewtabpage, thanks!

**Comment by tophf** [comment]
Add custom CSS in the options (the wrench tool icon):

```css
html:hover #main {
  opacity: 0;
  transition: opacity 1s ease-in-out .5s;
}

body:hover #main {
  opacity: 1;
}
```

It will make the page content fade out when the mouse is hovering the margins on the top or bottom.
